### PR TITLE
Contributing.md files updated

### PR DESCRIPTION
**Pull request by SusheelThapa**
As mentioned in #31 , I have update Contributing.md files including necessary images.

Please review, this PR and suggest me necessary changes.
@rudra016

### CODE REVIEW

**Comment by rudra016** [comment]
@SusheelThapa pls add screenshots

**Comment by SusheelThapa** [comment]
https://github.com/SusheelThapa/WebDev-OpenSource/blob/contributing/CONTRIBUTING.md

@rudra016, Above is the link to the update Contribution files. 

Adding Screenshoot will take 4 5 image so i have provided with link to updated contributing files

**Comment by rudra016** [comment]
@SusheelThapa 



Check thru my readme and add these two things on your code pls.youll find the code there just copy paste(banner at the top, contibuters at the end and then footer).

**Comment by SusheelThapa** [comment]
@rudra016  I have just updated Contribution.md files shall i update project Readme.md files too.

**Comment by rudra016** [comment]
yes

**Pull request merged**
