### PR TITLE
Added project:image editor

### PR DESCRIPTION
**Pull request by ira-mane**
Image Editor project using HTML, CSS, JS has been added along with readme file.

### CODE REVIEW

**Comment by Haris-Mohanty** [comment]
@ira-mane, Pls write more about your project with ss!

**Comment by rudra016** [comment]
@ira-mane Add some screenshots

**Comment by ira-mane** [comment]
> @ira-mane Add some screenshots

sure ,I will do it 👍

**Review by Haris-Mohanty — COMMENTED** [review]
Hey @ira-mane, Please add the Screenshots in the desc.

**Comment by ira-mane** [comment]
> Hey @ira-mane, Please add the Screenshots in the desc.

Hello , Can you please elaborate ,what do I have to do ?

**Pull request merged**
