### PR TITLE
Adding a cool 3D maze game

### PR DESCRIPTION
**Pull request by therealdhruv**
It's a very cool 3D games, with a simple tech stack of HTML, CSS and JS but quite a complex js script. It's a good project to understand the basics of rendering 3D images using vanilla js. 

Example Gameplay - 

https://github.com/rudra016/WebDev-OpenSource/assets/92241443/17412a79-afb5-46f6-9613-efc1c3905719

### CODE REVIEW

**Comment by therealdhruv** [comment]
Please do add the `hacktoberfest` and `hacktoberfest-accepted` tags ... Thank you Rudra 🥂

**Comment by rudra016** [comment]
Can your share some screenshots of the project

**Comment by therealdhruv** [comment]
> Can your share some screenshots of the project

even better, I've added an example gameplay 👍

**Comment by rudra016** [comment]
This is Amazing @therealdhruv Glad to merge!

**Pull request merged**
