### PR TITLE
Memory card game project added

### PR DESCRIPTION
**Pull request by Acesif**
This project showcases a memory card game made using HTML, CSS and JS.
In order to play this game, you need to match two hidden cards and match the same ones together.
image

### CODE REVIEW

**Comment by Acesif** [comment]
Please don't mind my commits, I accidentally included another project alongside the original PR. 
I have fixed the issue

**Review by Haris-Mohanty — CHANGES_REQUESTED** [review]
Hi @Acesif, add the description!

**Comment by Acesif** [comment]
@Haris-Mohanty Done

**Review by Haris-Mohanty — APPROVED** [review]

**Comment by Acesif** [comment]
Please merge if everything looks alright

**Comment by Acesif** [comment]
@rudra016 
Please merge if everything looks alright

**Pull request merged**
