### PR TITLE
added personal trainer app

### PR DESCRIPTION
**Pull request by 0silverback0**
This is a simple Personal Trainer business site. Built with HTML, CSS, and Javascript.

### CODE REVIEW

**Review by Haris-Mohanty — CHANGES_REQUESTED** [review]
Add the desc.

**Comment by 0silverback0** [comment]
where would you like it to be added in the code , or in the pull request title?

**Comment by Haris-Mohanty** [comment]
Yaa, pull req title and desc.

**Comment by 0silverback0** [comment]
I added a quick desc, let me know if it needs more detail

**Review by Haris-Mohanty — CHANGES_REQUESTED** [review]
Add some more info about your app with screenshots.

**Comment by 0silverback0** [comment]
This is a basic Personal Trainer web page template which images for your particular client can be easily added.  

Built with just HTML, and Bootstrap the web page is responsive and looks good on all device sizes. The site has a contact form which could create an email list for lead generation and promoting to current clients, if connected to a database. 

This site is just a template and should be customized according to the clients needs

Screenshot 2023-10-10 at 10 33 22 PM

Screenshot 2023-10-10 at 10 33 53 PM

**Review by Haris-Mohanty — APPROVED** [review]

**Review by Haris-Mohanty — APPROVED** [review]

**Pull request merged**
